# Test Notebook

In [1]:
import numpy as np
data = np.random.random((4, 4))
print(data)

[[0.37964198 0.39325297 0.93894365 0.70066526]
 [0.93548693 0.72915215 0.7717204  0.00636678]
 [0.50465197 0.0670144  0.62965692 0.50846681]
 [0.18276167 0.11813585 0.37960147 0.31669174]]
